services:
  backend:
    build: ./backend
    container_name: enrollment-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build: ./frontend
    container_name: enrollment-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
